### ISSUE TITLE
missing some ibc denoms

### ISSUE THREAD

**Issue by marslavish** [cosmology-tech/chain-registry#28]
e.g. `ibc/2F0984...8D96E3`

**Comment by pyramation** [comment]
hey @marslavish was this stargaze <> osmosis?

**Comment by pyramation** [comment]
https://github.com/cosmology-tech/chain-registry/commit/13660eb9b61eb1f30e44ec0fdd828a74ecd795df

**Comment by pyramation** [comment]
the missing hash is

```
ibc/2F0984925401F4DEBED91F26EE829050ECB5EA08ED2EB43207D55A3DF58D96E3
 ```
