### ISSUE TITLE
IBC asset lists

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/chain-registry#3]
currently there are three different asset lists I've been able to find, all with different styles:

- https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json
- https://github.com/scrtlabs/wrap.scrt.network/blob/master/src/config.ts
- https://github.com/CosmosContracts/junoswap-asset-list/blob/main/ibc_assets.json

Osmosis seems to be closest to the chain-registry style. We could start by generating lists like Osmosis', and maybe add `chain` and/or `counterparty` info. So far we've statically generated `ibc_assets.json` https://github.com/cosmology-finance/chain-registry/blob/main/packages/chain-registry/src/ibc_assets.json

- [ ] dynamically generate from a class and cache the data
- [ ] work with community on the best possible shape and API for consuming and working with IBC asset lists

**Comment by pyramation** [comment]
@JeremyParish69 

any thoughts on the structure we should have for `ibc_assets.json`? While I came up with the new idea [here](https://github.com/cosmology-finance/chain-registry/blob/main/packages/chain-registry/src/ibc_assets.json) The more I think about it, perhaps we should export something closer to the style of the Osmosis asset list which corresponds closely with chain-registry. 

Are there any other fields we should consider?

Also, if we can iron this stuff out here and get it tested, we can explore using these utils to generate some of these lists directly in the chain-registry repo.

**Comment by sascha1337** [comment]
[here is some json schema spec](https://registry.ping.pub/ibc_data.schema.json)
