### ISSUE TITLE
Missing `bWHALE` from `juno` asset list

### ISSUE THREAD

**Issue by NoahSaso** [cosmology-tech/chain-registry#34]
`IBC/01BAE2E69D02670B22758FBA74E4114B6E88FC1878936C919DA345E6C6C92ABF`

**Comment by pyramation** [comment]
this should go here: 
https://github.com/cosmos/chain-registry/blob/master/juno/assetlist.json

**Comment by pyramation** [comment]
we pull the assets from cosmos/chain-registry, and then import it in the build
