### ISSUE TITLE
Do not include the template in chain list

### ISSUE THREAD

**Issue by etienne-napoleone** [cosmology-tech/chain-registry#49]
currently, the template chain.json is included in the list of chains

https://github.com/cosmos/chain-registry/blob/22fe48a435116c77b8e1caef4466b4d75599c4bf/_template/chain.json#L81

**Comment by pyramation** [comment]
https://github.com/cosmology-tech/chain-registry/commit/fcfb6902130190d6de1d918d01bc02bc46bd2c5a
