### ISSUE TITLE
Spot outdated apis with a script/CI

### ISSUE THREAD

**Issue by AndreMiras** [cosmology-tech/chain-registry#53]
There're a few outdated apis (e.g. some in canto.apis.rest) URLs on different chains.
It should be relatively easy to spot them with a script to do a clean up.
Example of broken APIs:
- https://canto-rest.lgns.net:443 -> 502 bad gateway
- https://rest-canto.carbonZERO.zone:443 -> DNS resolution issue

I would he happy to work on that if you like. If you do let me know if there's a specific stack and direction (e.g. with CI, lerna...) you would like me to take.
The idea I have in mind is (each step has its own PR):

1) Write the script to spot outdated URLs. Start easy with rest endpoints that don't answer with a 200.
The script outputs the the OK vs KO ones and exits a non zero if any are KO.

2) Remove the broken endpoints from the registry.

3) Add the script to the CI (maybe on schedule) so that we can keep it clean preemptively.

**Comment by pyramation** [comment]
this is for the cosmos/chain-registry where we pull data from
