### ISSUE TITLE
Please update chain-registry to include dymension

### ISSUE THREAD

**Issue by phips28** [cosmology-tech/chain-registry#65]
How could I do this with a PR?

**Comment by HebeHe1986** [comment]
> How could I do this with a PR?

if you talking about the process of a request to merge code changes into the main code repository. you can refer to the below flows,

1. Clone the repository: First, you need to clone the project's code repository to your local development environment.
2. Create a branch: To submit your changes, you create a new branch. This ensures that your changes are based on the latest version of the main code repository.
3. Make changes: Work on your code modifications, add new features, or fix bugs on the new branch.
4. Commit changes: Once you are done with the code changes, commit them to your local branch.
5. Sync with the remote repository: Before pushing your changes to the remote repository, make sure your local branch is in sync with it.
6. Create a PR: Open the project repository on GitHub, and select "Create a new Pull Request." Choose your branch as the source and target branch, and provide a description of your changes.
7. Review: The project maintainers and other contributors will review your PR. They may provide suggestions, ask questions, or request changes.
8. Update as per feedback: Based on the review feedback, you may need to make modifications to your code or add new commits.
9. Merge the PR: Once your PR passes the review and meets all the necessary criteria, such as tests, the project maintainer will merge your changes into the main code repository.
10. Update your local repository: Once your changes are merged, you can fetch the latest changes and sync them with your local repository.

**Comment by phips28** [comment]
Nice bot 😄  

I just asked for the special case here for the chain-registry:
https://github.com/cosmology-tech/chain-registry/tree/main/packages/chain-registry

**Comment by phips28** [comment]
I see it got upgraded: https://github.com/cosmology-tech/chain-registry/commit/1910decbffc0099ffc03a5d2312922ac98301617
but no new release yet because tests failed.

@pyramation when are you able to publish it? 🙂
