### ISSUE TITLE
Couldn't find any versions for "@chain-registry/utils" that matches "^1.18.1" ? 

### ISSUE THREAD

**Issue by hbilandi** [cosmology-tech/chain-registry#71]
I am getting this error when I am updating my dependencies in package.json

Couldn't find any versions for "@chain-registry/utils" that matches "^1.18.1"
? Please choose a version of "@chain-registry/utils" from this list:
 1.18.0 
  1.17.3 
  1.17.1 
  1.17.0 
  1.16.1 
  1.16.0 
... so on

I am using yarn as a package manager and currently using v1.25.0 for @chain-registry/utils.

I got this error when I run below commands -

```
rm -rf node_modules
rm yarn.lock
yarn install (during this step)
```

**Comment by bilalmotiwala** [comment]
Hey folks! Same on this as well. Everything was perfectly fine before and now my app won't build because of this. Can someone please suggest a fix/workaround?

**Comment by Zetazzz** [comment]
Hi, we just successfully published a new version. please try 1.18.2.
I just tested and it works on my side.
Thank you very much!
