### ISSUE TITLE
"@chain-registry/types": "^0.18.4 doesn't exist. The latest version of chain-registy/types is 0.18.3

### ISSUE THREAD

**Issue by akhlopiachyi** [cosmology-tech/chain-registry#85]
Please update @chain-registry/types npm module version it 0.18.3, because it's the latest version of this package at the moment
Version 0.18.4 doesn't exist anymore

**Comment by akhlopiachyi** [comment]
@Zetazzz

**Comment by akhlopiachyi** [comment]
Currently chain-registry is a broken npm package, that cannot be used properly

**Comment by agonist** [comment]
Indeed everything broken

**Comment by Zetazzz** [comment]
There was sth wrong with the last publish, I just published them again:
 - @chain-registry/assets@1.34.6
 - chain-registry@1.33.6
 - @chain-registry/client@1.21.3
 - @chain-registry/cosmostation@1.36.6
 - @chain-registry/juno@1.34.6
 - @chain-registry/keplr@1.38.6
 - @chain-registry/osmosis@1.34.6
 - @chain-registry/types@0.18.5
 - @chain-registry/utils@1.19.4
